// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/exchange.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SubscribeEventRequest struct {
	Channel              string   `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeEventRequest) Reset()         { *m = SubscribeEventRequest{} }
func (m *SubscribeEventRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeEventRequest) ProtoMessage()    {}
func (*SubscribeEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8974edd908601500, []int{0}
}

func (m *SubscribeEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeEventRequest.Unmarshal(m, b)
}
func (m *SubscribeEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeEventRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeEventRequest.Merge(m, src)
}
func (m *SubscribeEventRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeEventRequest.Size(m)
}
func (m *SubscribeEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeEventRequest proto.InternalMessageInfo

func (m *SubscribeEventRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type DataReceiver struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Channel              string   `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	IsSuccess            bool     `protobuf:"varint,3,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataReceiver) Reset()         { *m = DataReceiver{} }
func (m *DataReceiver) String() string { return proto.CompactTextString(m) }
func (*DataReceiver) ProtoMessage()    {}
func (*DataReceiver) Descriptor() ([]byte, []int) {
	return fileDescriptor_8974edd908601500, []int{1}
}

func (m *DataReceiver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataReceiver.Unmarshal(m, b)
}
func (m *DataReceiver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataReceiver.Marshal(b, m, deterministic)
}
func (m *DataReceiver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataReceiver.Merge(m, src)
}
func (m *DataReceiver) XXX_Size() int {
	return xxx_messageInfo_DataReceiver.Size(m)
}
func (m *DataReceiver) XXX_DiscardUnknown() {
	xxx_messageInfo_DataReceiver.DiscardUnknown(m)
}

var xxx_messageInfo_DataReceiver proto.InternalMessageInfo

func (m *DataReceiver) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *DataReceiver) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *DataReceiver) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

type ActionRequest struct {
	Action               string   `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Market               string   `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	MessageId            int32    `protobuf:"varint,3,opt,name=messageId,proto3" json:"messageId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionRequest) Reset()         { *m = ActionRequest{} }
func (m *ActionRequest) String() string { return proto.CompactTextString(m) }
func (*ActionRequest) ProtoMessage()    {}
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8974edd908601500, []int{2}
}

func (m *ActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionRequest.Unmarshal(m, b)
}
func (m *ActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionRequest.Marshal(b, m, deterministic)
}
func (m *ActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionRequest.Merge(m, src)
}
func (m *ActionRequest) XXX_Size() int {
	return xxx_messageInfo_ActionRequest.Size(m)
}
func (m *ActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActionRequest proto.InternalMessageInfo

func (m *ActionRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *ActionRequest) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *ActionRequest) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

type HeathCheck struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeathCheck) Reset()         { *m = HeathCheck{} }
func (m *HeathCheck) String() string { return proto.CompactTextString(m) }
func (*HeathCheck) ProtoMessage()    {}
func (*HeathCheck) Descriptor() ([]byte, []int) {
	return fileDescriptor_8974edd908601500, []int{3}
}

func (m *HeathCheck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeathCheck.Unmarshal(m, b)
}
func (m *HeathCheck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeathCheck.Marshal(b, m, deterministic)
}
func (m *HeathCheck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeathCheck.Merge(m, src)
}
func (m *HeathCheck) XXX_Size() int {
	return xxx_messageInfo_HeathCheck.Size(m)
}
func (m *HeathCheck) XXX_DiscardUnknown() {
	xxx_messageInfo_HeathCheck.DiscardUnknown(m)
}

var xxx_messageInfo_HeathCheck proto.InternalMessageInfo

func (m *HeathCheck) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*SubscribeEventRequest)(nil), "exchange.SubscribeEventRequest")
	proto.RegisterType((*DataReceiver)(nil), "exchange.DataReceiver")
	proto.RegisterType((*ActionRequest)(nil), "exchange.ActionRequest")
	proto.RegisterType((*HeathCheck)(nil), "exchange.HeathCheck")
}

func init() { proto.RegisterFile("protos/exchange.proto", fileDescriptor_8974edd908601500) }

var fileDescriptor_8974edd908601500 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4d, 0x4f, 0xb3, 0x50,
	0x10, 0x85, 0xc3, 0xfb, 0x56, 0x6c, 0x27, 0xe2, 0xe2, 0xc6, 0x56, 0xd2, 0x98, 0xd8, 0x10, 0x17,
	0x5d, 0x51, 0x3f, 0x36, 0x2e, 0xfd, 0x6a, 0xa2, 0x71, 0x07, 0xbb, 0x26, 0x2e, 0x86, 0xdb, 0x49,
	0x21, 0x15, 0xa8, 0xdc, 0xa1, 0xf1, 0xa7, 0xfa, 0x73, 0x0c, 0xb7, 0x17, 0xaf, 0x24, 0x75, 0xc7,
	0x39, 0x9c, 0xf3, 0x84, 0x99, 0x01, 0x86, 0x9b, 0xaa, 0xe4, 0x52, 0xcd, 0xe8, 0x53, 0xa6, 0x58,
	0xac, 0x28, 0xd4, 0x5a, 0xf4, 0x5b, 0x1d, 0x5c, 0xc1, 0x30, 0xae, 0x13, 0x25, 0xab, 0x2c, 0xa1,
	0xf9, 0x96, 0x0a, 0x8e, 0xe8, 0xa3, 0x26, 0xc5, 0xc2, 0x87, 0xc3, 0x26, 0x52, 0xd0, 0xbb, 0xef,
	0x4c, 0x9c, 0xe9, 0x20, 0x6a, 0x65, 0xb0, 0x80, 0xa3, 0x27, 0x64, 0x8c, 0x48, 0x52, 0xb6, 0xa5,
	0x4a, 0x08, 0xe8, 0x2d, 0x91, 0xd1, 0xc4, 0xf4, 0xf3, 0xef, 0xf6, 0xbf, 0x4e, 0x5b, 0x9c, 0xc1,
	0x20, 0x53, 0x71, 0x2d, 0x25, 0x29, 0xe5, 0xff, 0x9f, 0x38, 0xd3, 0x7e, 0x64, 0x8d, 0xe0, 0x0d,
	0xbc, 0x7b, 0xc9, 0x59, 0x59, 0xb4, 0x9f, 0x31, 0x02, 0x17, 0xb5, 0x61, 0xf0, 0x46, 0x35, 0x7e,
	0x8e, 0xd5, 0x9a, 0xd8, 0xf0, 0x8d, 0x6a, 0xf0, 0x39, 0x29, 0x85, 0x2b, 0x7a, 0x59, 0x6a, 0xfc,
	0x41, 0x64, 0x8d, 0xe0, 0x02, 0xe0, 0x99, 0x90, 0xd3, 0xc7, 0x94, 0xe4, 0xba, 0x61, 0x28, 0x46,
	0xae, 0x55, 0xcb, 0xde, 0xa9, 0xeb, 0x2f, 0x07, 0xbc, 0xb9, 0x59, 0x50, 0xcc, 0x84, 0xb9, 0xb8,
	0x35, 0x3d, 0xa9, 0x7b, 0x27, 0xe1, 0xcf, 0x3a, 0x2d, 0x6d, 0xbc, 0xd7, 0x15, 0x77, 0xe0, 0x99,
	0x51, 0x76, 0x73, 0x89, 0x53, 0x1b, 0xeb, 0x4c, 0x3a, 0x1e, 0xd9, 0x17, 0x9d, 0xf5, 0xbe, 0xc2,
	0x71, 0xf7, 0x42, 0xe2, 0xdc, 0x26, 0xf7, 0xde, 0xee, 0x2f, 0xd4, 0xa5, 0xf3, 0xe0, 0x2e, 0x7a,
	0xe1, 0x6c, 0x93, 0x24, 0xae, 0xfe, 0x0f, 0x6e, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x36, 0xd6,
	0xd7, 0x9a, 0x20, 0x02, 0x00, 0x00,
}
