networks:
  internal-net:
    external: true
    driver: bridge

services:
  exchange:
    image: arthopacini/exchange:latest
    container_name: exchange
    restart: always
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - internal-net

  go-consumer:
    container_name: go-consumer-ws
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 80:50051
    expose:
      - 50051
    restart: always
    networks:
      - internal-net
